### ISSUE TITLE
Ruby 3.3 requires an explicit inclusion of racc gem in order to get this gem to work

### ISSUE THREAD

**Issue by karloscarweber** [danini-the-panini/kdl-rb#15]
Hi Friends.

I work on Camping, we use kdl instead of yard because kdl is cool. Anyways, upon updating to Ruby 3.3 `kdl` now requires the `racc` gem to be included in your bundler file in order to get it working. I'm not sure why. I know that `racc` is a development dependency, but it seems that it's also now a runtime dependency. ¯\_(ツ)_/¯  

You can view. A related issue here: https://github.com/camping/camping/issues/164.

I'm wondering if it would be cool to add the `racc` gem as a generic dependency so that upstream consumers of this library can get the gem when they `bundle install` along with `kdl`.

Thanks.

-kow

**Comment by danini-the-panini** [comment]
Fixed in v1.0.5

**Comment by karloscarweber** [comment]
You are a saint.
